export const DEFAULT_CATEGORIES = [
  { name: "Salary", type: "INCOME" as const },
  { name: "Freelance", type: "INCOME" as const },
  { name: "Bonus", type: "INCOME" as const },
  { name: "Investment", type: "INCOME" as const },
  { name: "Gift", type: "INCOME" as const },
  { name: "Food", type: "EXPENSE" as const },
  { name: "Transport", type: "EXPENSE" as const },
  { name: "Shopping", type: "EXPENSE" as const },
  { name: "Bills", type: "EXPENSE" as const },
  { name: "Rent", type: "EXPENSE" as const },
  { name: "Health", type: "EXPENSE" as const },
  { name: "Entertainment", type: "EXPENSE" as const },
  { name: "Education", type: "EXPENSE" as const },
  { name: "Travel", type: "EXPENSE" as const },
  { name: "Other", type: "EXPENSE" as const },
];
